# Generated by Django 3.2.16 on 2022-11-05 17:39

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', verbose_name='Текст'),
        ),
    ]
