# Generated by Django 3.2.16 on 2022-11-05 18:21

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221105_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', validators=[catalog.validators.validate_must_be_param]),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'Главное изображение',
                'verbose_name_plural': 'Главные изображения',
            },
        ),
    ]
