# Generated by Django 3.2.16 on 2022-11-07 16:57

import catalog.validators
from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20221105_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', validators=[catalog.validators.validate_must_be_param]),
        ),
    ]
