# Generated by Django 3.2.16 on 2022-11-12 20:05

import catalog.validators
from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', validators=[catalog.validators.validate_must_be_param]),
        ),
    ]
