# Generated by Django 3.2.16 on 2022-11-15 18:23

import markdownfield.models
from django.db import migrations

import catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20221114_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', validators=[catalog.validators.ValidateMustBeParam('превосходно', 'роскошно')]),
        ),
    ]
